# Generated by Django 3.2 on 2021-04-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_internalaccount_initial_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalaccount',
            name='account_number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
