# Generated by Django 4.0.3 on 2022-04-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20210501_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalaccount',
            name='branch_id',
        ),
    ]
