# Generated by Django 3.2 on 2021-04-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalaccount',
            name='initial_amount',
            field=models.IntegerField(default=0),
        ),
    ]
